import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 60;
export const dynamic = "force-dynamic";

export async function POST(request: NextRequest) {
  try {
    const { projectName, files, brandName } = await request.json();

    if (!projectName || !files?.length) {
      return NextResponse.json(
        { error: "projectName and files are required" },
        { status: 400 }
      );
    }

    const repoName = projectName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-");

    console.log("[github] Creating repo:", repoName);

    // Create the repository
    const createRepoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Modern rebuild of ${brandName} — generated by AutoAgency`,
        private: false,
        auto_init: true,
      }),
    });

    if (!createRepoRes.ok) {
      const error = await createRepoRes.text();
      throw new Error(`GitHub repo creation failed: ${error}`);
    }

    const repo = await createRepoRes.json();
    const fullName = repo.full_name;

    console.log("[github] Repo created:", fullName);

    // Wait a moment for GitHub to initialize the repo
    await new Promise((r) => setTimeout(r, 2000));

    // Push all generated files
    for (const file of files) {
      if (!file.name || !file.content) continue;

      const res = await fetch(
        `https://api.github.com/repos/${fullName}/contents/${file.name}`,
        {
          method: "PUT",
          headers: {
            Authorization: `token ${process.env.GITHUB_TOKEN}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            message: `Add ${file.name}`,
            content: Buffer.from(file.content).toString("base64"),
          }),
        }
      );

      if (!res.ok) {
        console.error(`[github] Failed to push ${file.name}:`, await res.text());
      }
    }

    // Add a README
    await fetch(
      `https://api.github.com/repos/${fullName}/contents/README.md`,
      {
        method: "PUT",
        headers: {
          Authorization: `token ${process.env.GITHUB_TOKEN}`,
          "Content-Type": "application/json",
          Accept: "application/vnd.github.v3+json",
        },
        body: JSON.stringify({
          message: "Add README",
          content: Buffer.from(
            `# ${brandName}\n\nModern website rebuild generated by [AutoAgency](https://auto-agency-three.vercel.app).\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
          ).toString("base64"),
        }),
      }
    );

    console.log("[github] All files pushed");

    return NextResponse.json({
      success: true,
      url: repo.html_url,
      fullName,
      repoName,
    });
  } catch (error) {
    console.error("[github] Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "GitHub push failed" },
      { status: 500 }
    );
  }
}
