import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 300;
export const dynamic = "force-dynamic";

interface ImageToSave {
  url: string;
  type: string;
  description?: string;
}

async function downloadImage(url: string): Promise<{ buffer: Buffer; extension: string } | null> {
  try {
    const response = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
      redirect: "follow",
    });

    if (!response.ok) {
      console.error(`[github] Failed to download image: ${url} (${response.status})`);
      return null;
    }

    const contentType = response.headers.get("content-type") || "";
    let extension = "jpg";
    if (contentType.includes("png")) extension = "png";
    else if (contentType.includes("svg")) extension = "svg";
    else if (contentType.includes("webp")) extension = "webp";
    else if (contentType.includes("gif")) extension = "gif";
    else if (url.match(/\.(png|jpg|jpeg|svg|webp|gif)/i)) {
      const match = url.match(/\.(png|jpg|jpeg|svg|webp|gif)/i);
      if (match) extension = match[1].toLowerCase();
      if (extension === "jpeg") extension = "jpg";
    }

    const buffer = Buffer.from(await response.arrayBuffer());

    // Skip tiny images (likely tracking pixels) and huge ones
    if (buffer.length < 500 || buffer.length > 10_000_000) {
      return null;
    }

    return { buffer, extension };
  } catch (error) {
    console.error(`[github] Error downloading ${url}:`, error);
    return null;
  }
}

function getImageFilename(type: string, index: number, extension: string): string {
  switch (type) {
    case "logo":
      return `logo.${extension}`;
    case "hero":
      return `hero.${extension}`;
    case "team":
      return `team-${index + 1}.${extension}`;
    case "product":
      return `product-${index + 1}.${extension}`;
    case "testimonial":
      return `testimonial-${index + 1}.${extension}`;
    case "gallery":
      return `gallery-${index + 1}.${extension}`;
    case "icon":
      return `icon-${index + 1}.${extension}`;
    default:
      return `image-${index + 1}.${extension}`;
  }
}

export async function POST(request: NextRequest) {
  try {
    const { projectName, files, brandName, images } = await request.json();

    if (!projectName || !files?.length) {
      return NextResponse.json(
        { error: "projectName and files are required" },
        { status: 400 }
      );
    }

    const repoName = projectName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-");

    console.log("[github] Creating repo:", repoName);

    // Create the repository
    const createRepoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Modern rebuild of ${brandName} — generated by ClientFactory`,
        private: false,
        auto_init: true,
      }),
    });

    if (!createRepoRes.ok) {
      const error = await createRepoRes.text();
      throw new Error(`GitHub repo creation failed: ${error}`);
    }

    const repo = await createRepoRes.json();
    const fullName = repo.full_name;

    console.log("[github] Repo created:", fullName);

    // Wait for GitHub to initialize
    await new Promise((r) => setTimeout(r, 2000));

    // Push all generated code files
    for (const file of files) {
      if (!file.name || !file.content) continue;

      const res = await fetch(
        `https://api.github.com/repos/${fullName}/contents/${file.name}`,
        {
          method: "PUT",
          headers: {
            Authorization: `token ${process.env.GITHUB_TOKEN}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            message: `Add ${file.name}`,
            content: Buffer.from(file.content).toString("base64"),
          }),
        }
      );

      if (!res.ok) {
        console.error(`[github] Failed to push ${file.name}:`, await res.text());
      }
    }

    // Download and push images to public/images/
    const imageList: ImageToSave[] = images || [];
    const typeCounts: Record<string, number> = {};
    let savedImages = 0;

    if (imageList.length > 0) {
      console.log(`[github] Downloading ${imageList.length} images...`);

      for (const img of imageList) {
        const result = await downloadImage(img.url);
        if (!result) continue;

        // Track count per type for naming
        const type = img.type || "other";
        typeCounts[type] = (typeCounts[type] || 0);
        const filename = getImageFilename(type, typeCounts[type], result.extension);
        typeCounts[type]++;

        const filePath = `public/images/${filename}`;

        const res = await fetch(
          `https://api.github.com/repos/${fullName}/contents/${filePath}`,
          {
            method: "PUT",
            headers: {
              Authorization: `token ${process.env.GITHUB_TOKEN}`,
              "Content-Type": "application/json",
              Accept: "application/vnd.github.v3+json",
            },
            body: JSON.stringify({
              message: `Add ${filePath}`,
              content: result.buffer.toString("base64"),
            }),
          }
        );

        if (res.ok) {
          savedImages++;
        } else {
          console.error(`[github] Failed to push ${filePath}:`, await res.text());
        }
      }

      console.log(`[github] Saved ${savedImages}/${imageList.length} images`);
    }

    // Add README
    await fetch(
      `https://api.github.com/repos/${fullName}/contents/README.md`,
      {
        method: "PUT",
        headers: {
          Authorization: `token ${process.env.GITHUB_TOKEN}`,
          "Content-Type": "application/json",
          Accept: "application/vnd.github.v3+json",
        },
        body: JSON.stringify({
          message: "Add README",
          content: Buffer.from(
            `# ${brandName}\n\nModern website rebuild generated by [ClientFactory](https://auto-agency-three.vercel.app).\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Images\n\nAll scraped images are saved in \`public/images/\`.\n`
          ).toString("base64"),
        }),
      }
    );

    console.log("[github] All files pushed");

    return NextResponse.json({
      success: true,
      url: repo.html_url,
      fullName,
      repoName,
      imagesSaved: savedImages,
    });
  } catch (error) {
    console.error("[github] Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "GitHub push failed" },
      { status: 500 }
    );
  }
}
