import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 300;
export const dynamic = "force-dynamic";

interface ImageToSave {
  url: string;
  type: string;
  description?: string;
}

async function downloadImage(url: string): Promise<{ buffer: Buffer; extension: string } | null> {
  try {
    const response = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
      redirect: "follow",
    });

    if (!response.ok) {
      console.error(`[github] Failed to download image: ${url} (${response.status})`);
      return null;
    }

    const contentType = response.headers.get("content-type") || "";
    let extension = "jpg";
    if (contentType.includes("png")) extension = "png";
    else if (contentType.includes("svg")) extension = "svg";
    else if (contentType.includes("webp")) extension = "webp";
    else if (contentType.includes("gif")) extension = "gif";
    else if (url.match(/\.(png|jpg|jpeg|svg|webp|gif)/i)) {
      const match = url.match(/\.(png|jpg|jpeg|svg|webp|gif)/i);
      if (match) extension = match[1].toLowerCase();
      if (extension === "jpeg") extension = "jpg";
    }

    const buffer = Buffer.from(await response.arrayBuffer());

    // Skip tiny images (likely tracking pixels) and huge ones
    if (buffer.length < 500 || buffer.length > 10_000_000) {
      return null;
    }

    return { buffer, extension };
  } catch (error) {
    console.error(`[github] Error downloading ${url}:`, error);
    return null;
  }
}

function getImageFilename(type: string, index: number, extension: string): string {
  switch (type) {
    case "logo":
      return `logo.${extension}`;
    case "hero":
      return `hero.${extension}`;
    case "team":
      return `team-${index + 1}.${extension}`;
    case "product":
      return `product-${index + 1}.${extension}`;
    case "testimonial":
      return `testimonial-${index + 1}.${extension}`;
    case "gallery":
      return `gallery-${index + 1}.${extension}`;
    case "icon":
      return `icon-${index + 1}.${extension}`;
    default:
      return `image-${index + 1}.${extension}`;
  }
}

export async function POST(request: NextRequest) {
  try {
    const { projectName, files, brandName, images } = await request.json();

    if (!projectName || !files?.length) {
      return NextResponse.json(
        { error: "projectName and files are required" },
        { status: 400 }
      );
    }

    const repoName = projectName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-");

    console.log("[github] Creating repo:", repoName);

    // Try to create the repository — if it already exists, we'll update it
    const createRepoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Modern rebuild of ${brandName} — generated by RefreshFactory.ai`,
        private: false,
        auto_init: true,
      }),
    });

    let fullName: string;
    let repoUrl: string;

    if (createRepoRes.ok) {
      const repo = await createRepoRes.json();
      fullName = repo.full_name;
      repoUrl = repo.html_url;
      console.log("[github] Repo created:", fullName);
      // Wait for GitHub to initialize new repo
      await new Promise((r) => setTimeout(r, 2000));
    } else {
      // Repo likely already exists — use it
      const owner = process.env.GITHUB_OWNER || "coreyfmiller";
      fullName = `${owner}/${repoName}`;
      repoUrl = `https://github.com/${fullName}`;
      console.log("[github] Repo already exists, updating:", fullName);
    }

    // Determine which scaffold files are needed (only add if v0 didn't provide them)
    const fileNames = new Set(files.map((f: { name: string }) => f.name));
    const scaffoldFiles: { name: string; content: string }[] = [];

    if (!fileNames.has("next.config.mjs") && !fileNames.has("next.config.js") && !fileNames.has("next.config.ts")) {
      scaffoldFiles.push({
        name: "next.config.mjs",
        content: `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  images: {\n    unoptimized: true,\n  },\n}\n\nexport default nextConfig\n`,
      });
    }

    if (!fileNames.has("tsconfig.json")) {
      scaffoldFiles.push({
        name: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }],
            paths: { "@/*": ["./*"] },
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        }, null, 2) + "\n",
      });
    }

    if (!fileNames.has("tailwind.config.ts") && !fileNames.has("tailwind.config.js")) {
      // Tailwind v4 doesn't need a config file — config is in CSS
      // Only add if v0 didn't provide one
    }

    if (!fileNames.has("postcss.config.mjs") && !fileNames.has("postcss.config.js")) {
      scaffoldFiles.push({
        name: "postcss.config.mjs",
        content: `/** @type {import('postcss-load-config').Config} */\nconst config = {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n}\n\nexport default config\n`,
      });
    }

    if (!fileNames.has(".gitignore")) {
      scaffoldFiles.push({
        name: ".gitignore",
        content: "node_modules\n.next\n.env*.local\n",
      });
    }

    if (!fileNames.has("lib/utils.ts")) {
      scaffoldFiles.push({
        name: "lib/utils.ts",
        content: `import { type ClassValue, clsx } from "clsx"\nimport { twMerge } from "tailwind-merge"\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs))\n}\n`,
      });
    }

    if (!fileNames.has("package.json")) {
      scaffoldFiles.push({
        name: "package.json",
        content: JSON.stringify({
          name: repoName,
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^14",
            react: "^18",
            "react-dom": "^18",
            "lucide-react": "^0.400",
            tailwindcss: "^4",
            "@tailwindcss/postcss": "^4",
            "class-variance-authority": "^0.7",
            clsx: "^2",
            "tailwind-merge": "^2",
            autoprefixer: "^10",
            postcss: "^8",
            typescript: "^5",
            "@types/node": "^20",
            "@types/react": "^18",
            "@types/react-dom": "^18",
          },
        }, null, 2) + "\n",
      });
    }

    // Combine v0 files + scaffold files
    const allFiles = [...files, ...scaffoldFiles];

    // Push all files (get SHA first if file exists for updates)
    for (const file of allFiles) {
      if (!file.name || !file.content) continue;

      // Check if file already exists to get its SHA
      let sha: string | undefined;
      const existingRes = await fetch(
        `https://api.github.com/repos/${fullName}/contents/${file.name}`,
        {
          headers: {
            Authorization: `token ${process.env.GITHUB_TOKEN}`,
            Accept: "application/vnd.github.v3+json",
          },
        }
      );
      if (existingRes.ok) {
        const existing = await existingRes.json();
        sha = existing.sha;
      }

      const res = await fetch(
        `https://api.github.com/repos/${fullName}/contents/${file.name}`,
        {
          method: "PUT",
          headers: {
            Authorization: `token ${process.env.GITHUB_TOKEN}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            message: sha ? `Update ${file.name}` : `Add ${file.name}`,
            content: Buffer.from(file.content).toString("base64"),
            ...(sha ? { sha } : {}),
          }),
        }
      );

      if (!res.ok) {
        console.error(`[github] Failed to push ${file.name}:`, await res.text());
      }
    }

    // Download and push images to public/images/
    const imageList: ImageToSave[] = images || [];
    const typeCounts: Record<string, number> = {};
    let savedImages = 0;

    if (imageList.length > 0) {
      console.log(`[github] Downloading ${imageList.length} images...`);

      for (const img of imageList) {
        const result = await downloadImage(img.url);
        if (!result) continue;

        // Track count per type for naming
        const type = img.type || "other";
        typeCounts[type] = (typeCounts[type] || 0);
        const filename = getImageFilename(type, typeCounts[type], result.extension);
        typeCounts[type]++;

        const filePath = `public/images/${filename}`;

        const res = await fetch(
          `https://api.github.com/repos/${fullName}/contents/${filePath}`,
          {
            method: "PUT",
            headers: {
              Authorization: `token ${process.env.GITHUB_TOKEN}`,
              "Content-Type": "application/json",
              Accept: "application/vnd.github.v3+json",
            },
            body: JSON.stringify({
              message: `Add ${filePath}`,
              content: result.buffer.toString("base64"),
            }),
          }
        );

        if (res.ok) {
          savedImages++;
        } else {
          console.error(`[github] Failed to push ${filePath}:`, await res.text());
        }
      }

      console.log(`[github] Saved ${savedImages}/${imageList.length} images`);
    }

    // Add README
    await fetch(
      `https://api.github.com/repos/${fullName}/contents/README.md`,
      {
        method: "PUT",
        headers: {
          Authorization: `token ${process.env.GITHUB_TOKEN}`,
          "Content-Type": "application/json",
          Accept: "application/vnd.github.v3+json",
        },
        body: JSON.stringify({
          message: "Add README",
          content: Buffer.from(
            `# ${brandName}\n\nModern website rebuild generated by [RefreshFactory.ai](https://auto-agency-three.vercel.app).\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Images\n\nAll scraped images are saved in \`public/images/\`.\n`
          ).toString("base64"),
        }),
      }
    );

    console.log("[github] All files pushed");

    return NextResponse.json({
      success: true,
      url: repoUrl,
      fullName,
      repoName,
      imagesSaved: savedImages,
    });
  } catch (error) {
    console.error("[github] Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "GitHub push failed" },
      { status: 500 }
    );
  }
}
